#!/bin/bash
#
# Activate the Spack environment for developing NESO and set some
# environment variables. This script should be sourced to activate
# the environment. You can then run the "deactivate" function to
# return to your previous setup.
#

deactivate() {
  export I_MPI_FABRICS=$__ORIGINAL_I_MPI_FABRICS
  export SYCL_DEVICE_FILTER=$__ORIGINAL_SYCL_DEVICE_FILTER

  unset $__ORIGINAL_I_MPI_FABRICS
  unset $__ORIGINAL_SYCL_DEVICE_FILTER
  
  spack env deactivate
  unset -f deactivate
}

spack env activate -p -d $(dirname $BASH_SOURCE)

export __ORIGINAL_I_MPI_FABRICS=$I_MPI_FABRICS
export __ORIGINAL_SYCL_DEVICE_FILTER=$SYCL_DEVICE_FILTER

export I_MPI_FABRICS=shm
export SYCL_DEVICE_FILTER=host
